Lesson3
ToporovV/geekshop-server pull request #3
Opened 2021-06-05 11:46 UTC by ToporovV

2021-06-07 07:43 UTC, Vokler requested changes

2021-06-07 07:43 UTC, Vokler commented on products/views.py
> +        'products': Product.objects.all(),
Добавьте сюда вывод категорий еще

2021-06-07 15:38 UTC, ToporovV commented on products/views.py
> +        'products': Product.objects.all(),
Добавил вывод категорий

2021-06-08 07:09 UTC, Vokler approved these changes

2021-06-08 07:09 UTC, merged