Lesson7 8
ToporovV/geekshop-server pull request #7
Opened 2021-06-23 21:31 UTC by ToporovV

Здравствуйте, Валерий, посмотрите пожалуйста контроллер приложения products. Не могу понять почему в классе ProductsListView(ListView) (закоментрованно) не отображаются сами карточки продуктов на странице.

2021-06-24 07:39 UTC, Vokler requested changes

2021-06-24 07:39 UTC, Vokler commented on products/templates/products/products.html
> +                        {% for page in products.paginator.page_range %}
У вас не отображаются товары, потому что нет ключа `products`. Если вы используете `ListView()`, то нужно использовать `objects_list`, как мы это делали в `admins/admin_users.html`

2021-06-25 03:50 UTC, ToporovV commented on products/templates/products/products.html
> +                        {% for page in products.paginator.page_range %}
Добавил objects_list и пагинацию в products.html

2021-06-25 10:13 UTC, Vokler approved these changes

2021-06-25 10:13 UTC, merged